---
- name: Install core packages
  become: true
  ansible.builtin.apt:
    name:
      - git
      - tmux
      - curl
      - wget
      - make
      - tar
      - zip
      - unzip
      - bzip2
      - openssl
      - sshfs
      - gnupg
      - zsh
      - diffutils
      - cppcheck
      - jq
      - build-essential
    state: present
  when: ansible_os_family == "Debian"
