---
- name: Download target release {{ target_nvim_ver }}
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ target_nvim_ver }}/nvim-linux64.tar.gz"
    dest: "{{ tmp_folder_path }}/nvim-linux64.tar.gz"
    mode: "0644"

- name: Extract from archive
  ansible.builtin.unarchive:
    src: "{{ tmp_folder_path }}/nvim-linux64.tar.gz"
    dest: "{{ tmp_folder_path }}"
    remote_src: true
    creates: "{{ tmp_folder_path }}/nvim-linux64"

- name: Copy bin to {{ target_local_bin_path }}
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tmp_folder_path }}/nvim-linux64/bin/nvim"
    dest: "{{ target_local_bin_path }}"
    mode: "0755"

- name: Copy share to {{ target_local_share_path }}
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tmp_folder_path }}/nvim-linux64/share/nvim"
    dest: "{{ target_local_share_path }}"
    mode: "0755"

- name: Copy lib to {{ target_local_lib_path }}
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tmp_folder_path }}/nvim-linux64/lib/nvim"
    dest: "{{ target_local_lib_path }}"
    mode: "0755"
