FROM ubuntu:latest

ARG USER=${USER}

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install --no-install-recommends \
    sudo \
    adduser \
    openssh-server \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m ${USER} && \
    adduser ${USER} sudo && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudoers

USER "${USER}"
RUN mkdir ~/.ssh && chmod 700 ~/.ssh
COPY --chown=${USER}:sudo id_rsa.pub /home/${USER}/.ssh/id_rsa.pub
RUN cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
RUN chmod 644 ~/.ssh/id_rsa.pub && chmod 644 ~/.ssh/authorized_keys

USER root
RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
