---
- name: Set target architecture
  ansible.builtin.set_fact:
    target_arch: "{{ ansible_architecture | replace('x86_64', 'amd64') }}"

- name: Set target os
  ansible.builtin.set_fact:
    target_os: "{{ ansible_os_family | replace('Debian', 'linux') | replace('Darwin', 'macos') }}"

- name: Set archive file name
  ansible.builtin.set_fact:
    fastfetch_archive_name: "fastfetch-{{ target_os }}-{{ target_arch }}"
  when: target_os != 'macos'

- name: Set archive file name for macOS
  ansible.builtin.set_fact:
    fastfetch_archive_name: "fastfetch-macos-universal"
  when: target_os == 'macos'

- name: Download target release {{ target_fastfetch_ver }}
  ansible.builtin.get_url:
    url: "https://github.com/fastfetch-cli/fastfetch/releases/download/{{ target_fastfetch_ver }}/{{ fastfetch_archive_name }}.tar.gz"
    dest: "{{ tmp_folder_path }}/fastfetch.tar.gz"
    mode: "0644"

- name: Extract from archive
  ansible.builtin.unarchive:
    src: "{{ tmp_folder_path }}/fastfetch.tar.gz"
    dest: "{{ tmp_folder_path }}"
    remote_src: true
    creates: "{{ tmp_folder_path }}/{{ fastfetch_archive_name }}"

- name: Copy bin to {{ target_local_bin_path }}
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tmp_folder_path }}/{{ fastfetch_archive_name }}/usr/bin/fastfetch"
    dest: "{{ target_local_bin_path }}"
    mode: "0755"
