---
- name: Set target architecture
  ansible.builtin.set_fact:
    target_arch: "{{ ansible_architecture }}"

- name: Set target os
  ansible.builtin.set_fact:
    target_os: "{{ ansible_os_family | replace('Debian', 'linux-musl') }}"

- name: Download target version {{ target_btop_ver }}
  ansible.builtin.get_url:
    url: "https://github.com/aristocratos/btop/releases/download/{{ target_btop_ver }}/btop-{{ target_arch }}-{{ target_os }}.tbz"
    dest: "{{ tmp_folder_path }}/btop.tbz"
    mode: "0644"

- name: Extract from archive
  ansible.builtin.unarchive:
    src: "{{ tmp_folder_path }}/btop.tbz"
    dest: "{{ tmp_folder_path }}"
    remote_src: true
    creates: "{{ tmp_folder_path }}/btop"

- name: Install to {{ target_local_path }}
  become: true
  community.general.make:
    chdir: "{{ tmp_folder_path }}/btop"
    target: install
    params:
      PREFIX: "{{ target_local_path }}"
