---
- name: Set target architecture
  ansible.builtin.set_fact:
    target_arch: "{{ ansible_architecture }}"

- name: Set target os
  ansible.builtin.set_fact:
    target_os: "{{ ansible_os_family | replace('Debian', 'linux') | replace('Darwin', 'mac') }}"

- name: Download target version {{ target_procs_ver }}
  ansible.builtin.get_url:
    url: "https://github.com/dalance/procs/releases/download/{{ target_procs_ver }}/procs-{{ target_procs_ver }}-{{ target_arch }}-{{ target_os }}.zip"
    dest: "{{ tmp_folder_path }}/procs.zip"
    mode: "0644"
  when: install_procs

- name: Extract from archive
  ansible.builtin.unarchive:
    src: "{{ tmp_folder_path }}/procs.zip"
    dest: "{{ tmp_folder_path }}"
    remote_src: true
    creates: "{{ tmp_folder_path }}/procs"
  when: install_procs

- name: Copy to {{ target_local_bin_path }}
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tmp_folder_path }}/procs"
    dest: "{{ target_local_bin_path }}"
    mode: "0755"
  when: install_procs
