gui:
  sidePanelWidth: 0.2
  theme:
    selectedLineBgColor:
      - reverse
  branchColors:
    "master": "#E2DFD0"
    "main": "#E2DFD0"
    "dev": "#AD49E1"
    "develop": "#AD49E1"
    "nightly": "#AD49E1"
    "integration": "#8DA9C4"
    "int": "#8DA9C4"
    "feat": "#90EE90"
    "feature": "#90EE90"
    "fix": "#ce5a57"
    "hotfix": "#ce5a57"
    "bugfix": "#ce5a57"
    "release": "#e1b16a"
  nerdFontsVersion: "3"
os:
  editPreset: "nvim-remote"
git:
  paging:
    colorArg: always
    useConfig: true
