gui:
  sidePanelWidth: 0.2
  theme:
    selectedLineBgColor:
      - reverse
  branchColors:
    "master": "#E2DFD0"
    "main": "#E2DFD0"
    "integration": "#8DA9C4"
    "int": "#8DA9C4"
    "dev": "#F97300"
    "develop": "#F97300"
    "feat": "#009B72"
    "feature": "#009B72"
    "fix": "#F03A47"
    "hotfix": "#F03A47"
    "release": "#F4E04D"
  nerdFontsVersion: "3"
os:
  editPreset: "nvim-remote"
git:
  paging:
    colorArg: always
    useConfig: true
