---
- name: Install dependencies using apt
  become: true
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - unzip
      - curl
      - build-essential
      - ccache
      - cmake
