---
- name: Run debian based setup
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install packages
  ansible.builtin.pip:
    name: "{{ python_pkg }}"
    state: present
    # extra_args: --break-system-packages
  loop: "{{ python_pkgs }}"
  loop_control:
    loop_var: python_pkg
  when: python_pkgs is defined
