---
- name: Run debian based setup
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install packages
  ansible.builtin.pip:
    name: "{{ python_pkg }}"
    state: present
    extra_args: "{{ '--break-system-packages' if pip_break_system_packages is defined else '' }}"
  loop: "{{ python_pkgs }}"
  loop_control:
    loop_var: python_pkg
  when: python_pkgs is defined
