---
- name: Install core packages
  become: true
  ansible.builtin.apt:
    name:
      - git
      - tmux
      - curl
      - wget
      - make
      - tar
      - zip
      - unzip
      - openssl
      - sshfs
      - gnupg
      - zsh
      - bat
      - fzf
      - fd-find
      - ripgrep
      - diffutils
      - btop
      - cppcheck
      - bat
      - jq
    state: present
  when: ansible_os_family == "Debian"
