---
- name: Get latest raw data
  ansible.builtin.uri:
    url: https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest
  register: latest_zoxide_raw_data
  changed_when: false

- name: Get latest version
  ansible.builtin.set_fact:
    latest_zoxide_ver: "{{ latest_zoxide_raw_data.json.tag_name }}"

- name: Get system version
  ansible.builtin.shell:
    cmd: set -o pipefail && $(which zoxide) --version | grep -oP '\d+\.\d+\.\d+' | sed 's/^/v/'
  args:
    executable: /bin/bash
  register: sys_zoxide_ver
  changed_when: false
  failed_when: false

- name: Get target version according to locked configuration
  ansible.builtin.set_fact:
    target_zoxide_ver: "{{ zoxide.version }}"
  when: zoxide.version is defined and zoxide.version != 'latest'

- name: Set target version to latest {{ latest_zoxide_ver }}
  ansible.builtin.set_fact:
    target_zoxide_ver: "{{ latest_zoxide_ver }}"
  when: target_zoxide_ver is not defined

- name: Set validity for installation
  ansible.builtin.set_fact:
    install_zoxide: "{{ sys_zoxide_ver.stdout != target_zoxide_ver }}"

- name: Show versions and installation status
  ansible.builtin.debug:
    msg:
      - "locked version             : {{ zoxide.version if zoxide.version is defined else '' }}"
      - "system version             : {{ sys_zoxide_ver.stdout }}"
      - "latest version             : {{ latest_zoxide_ver }}"
      - "should install/update      : {{ install_zoxide }}"
      - "install version            : {{ target_zoxide_ver if install_zoxide else '' }}"

- name: Installation
  when: install_zoxide
  block:
    - name: Set target architecture
      ansible.builtin.set_fact:
        target_arch: "{{ ansible_architecture }}"

    - name: Set target os
      ansible.builtin.set_fact:
        target_os: "{{ ansible_os_family | replace('Debian', 'unknown-linux-musl') | replace('Darwin', 'apple-darwin') }}"

    - name: Set zoxide_archive_name
      ansible.builtin.set_fact:
        zoxide_archive_name: "zoxide-{{ target_zoxide_ver | regex_replace('^v', '') }}-{{ target_arch }}-{{ target_os }}.tar.gz"

    - name: Download target version {{ target_zoxide_ver }}
      ansible.builtin.get_url:
        url: "https://github.com/ajeetdsouza/zoxide/releases/download/{{ target_zoxide_ver }}/{{ zoxide_archive_name }}"
        dest: "{{ tmp_folder_path }}/zoxide.tar.gz"
        mode: "0644"

    - name: Create destination folder
      ansible.builtin.file:
        path: "{{ tmp_folder_path }}/zoxide"
        state: directory
        mode: "0755"

    - name: Extract from archive
      ansible.builtin.unarchive:
        src: "{{ tmp_folder_path }}/zoxide.tar.gz"
        dest: "{{ tmp_folder_path }}/zoxide"
        remote_src: true
        creates: "{{ tmp_folder_path }}/zoxide/zoxide"

    - name: Copy to {{ target_local_bin_path }}
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: "{{ tmp_folder_path }}/zoxide/zoxide"
        dest: "{{ target_local_bin_path }}"
        mode: "0755"

    - name: Copy zsh completion file to {{ zsh_completions_path }}
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: "{{ tmp_folder_path }}/zoxide/completions/_zoxide"
        dest: "{{ zsh_completions_path }}"
        mode: "0644"
