---
- name: Get latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/sharkdp/fd/releases/latest
  register: latest_fd_raw_data
  changed_when: false

- name: Get latest version
  ansible.builtin.set_fact:
    latest_fd_ver: "{{ latest_fd_raw_data.json.tag_name }}"

- name: Get system version
  ansible.builtin.shell:
    cmd: set -o pipefail && $(which fd) --version | grep -oP '\d+\.\d+\.\d+' | sed 's/^/v/'
  args:
    executable: /bin/bash
  register: sys_fd_ver
  changed_when: false
  failed_when: false

- name: Fix locked version by adding 'v' prefix
  ansible.builtin.set_fact:
    fd:
      version: "v{{ fd.version }}"
  when: fd.version is defined and fd.version | regex_search('^\d')

- name: Get target version according to locked configuration
  ansible.builtin.set_fact:
    target_fd_ver: "{{ fd.version }}"
  when: fd.version is defined and fd.version != 'latest'

- name: Set target version to latest {{ latest_fd_ver }}
  ansible.builtin.set_fact:
    target_fd_ver: "{{ latest_fd_ver }}"
  when: target_fd_ver is not defined

- name: Set validity for installation
  ansible.builtin.set_fact:
    install_fd: "{{ sys_fd_ver.stdout != target_fd_ver }}"

- name: Show versions and installation status
  ansible.builtin.debug:
    msg:
      - "locked version             : {{ fd.version if fd.version is defined else '' }}"
      - "system version             : {{ sys_fd_ver.stdout }}"
      - "latest version             : {{ latest_fd_ver }}"
      - "should install/update      : {{ install_fd }}"
      - "install version            : {{ target_fd_ver if install_fd else '' }}"

- name: Installation by extraction binaries
  when: install_fd
  block:
    - name: Set target architecture
      ansible.builtin.set_fact:
        target_arch: "{{ ansible_architecture | replace('arm64', 'aarch64') }}"

    - name: Set target os
      ansible.builtin.set_fact:
        target_os: "{{ ansible_os_family | replace('Debian', 'unknown-linux-gnu') | replace('Darwin', 'apple-darwin') }}"

    - name: Set archive file name
      ansible.builtin.set_fact:
        target_archive_name: "fd-{{ target_fd_ver }}-{{ target_arch }}-{{ target_os }}.tar.gz"

    - name: Download target version {{ target_fd_ver }}
      ansible.builtin.get_url:
        url: "https://github.com/sharkdp/fd/releases/download/{{ target_fd_ver }}/{{ target_archive_name }}"
        dest: "{{ tmp_folder_path }}/fd.tar.gz"
        mode: "0644"

    - name: Extract from archive
      ansible.builtin.unarchive:
        src: "{{ tmp_folder_path }}/fd.tar.gz"
        dest: "{{ tmp_folder_path }}"
        remote_src: true
        creates: "{{ tmp_folder_path }}/fd-{{ target_fd_ver }}-{{ target_arch }}-{{ target_os }}/fd"

    - name: Copy to {{ target_local_bin_path }}
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: "{{ tmp_folder_path }}/fd-{{ target_fd_ver }}-{{ target_arch }}-{{ target_os }}/fd"
        dest: "{{ target_local_bin_path }}"
        mode: "0755"

    - name: Copy zsh completion file to {{ zsh_completions_path }}
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: "{{ tmp_folder_path }}/fd-{{ target_fd_ver }}-{{ target_arch }}-{{ target_os }}/autocomplete/_fd"
        dest: "{{ zsh_completions_path }}"
        mode: "0644"
